name: Publish spec package to GitHub packages

on:
  push:
    branches: [ 'stable' ]
    paths:
      - spec/**


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yamusic-docs

jobs:
  build-and-push-image:
    name: Build and push Docker image to Github Packages

    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./spec
          file: ./spec/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
