name: Test the OpenAPI specification

on:
  pull_request:
    branches:
      - stable
    paths:
      - spec/**

defaults:
  run:
    working-directory: spec

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Run Prettier
        run: npm run format:verify
      - name: Run ESLint
        run: npm run lint
      - name: Run build
        run: npm run build
